title: test title
author: ho hum
email: test email
description: > # this means to ignore newlines until "baseurl:"
  I guess this will appear in the google search meta

# social links
twitter_username: twerksmith
github_username:  twerksmith

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
